apiVersion: v1
kind: Service
metadata:
  name: edgemonitor
  namespace: edgemonitor
  labels:
    app: edgemonitor
spec:
  selector:
    app: edgemonitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
